# DB config
db.url=jdbc:mysql://localhost:3306/automation_results?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
db.user=root
db.password=admin123

browser=chrome
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
